[project]
name = 'axelar'
description = ''
authors = []
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[contracts.traits]
path = 'contracts/traits.clar'

[contracts.gas-storage]
path = 'contracts/gas-storage.clar'
depends_on = ['traits']
clarity_version = 2
epoch = 2.5

[contracts.gas-impl]
path = 'contracts/gas-impl.clar'
depends_on = ['traits', 'gas-storage']
clarity_version = 2
epoch = 2.5

[contracts.gas-service]
path = 'contracts/gas-service.clar'
depends_on = ['traits', 'gas-impl', 'gas-storage']
clarity_version = 2
epoch = 2.5

[contracts.gateway]
path = 'contracts/gateway.clar'
clarity_version = 2
epoch = 2.5

[contracts.gateway-impl]
path = 'contracts/gateway-impl.clar'
clarity_version = 2
epoch = 2.5

[contracts.gateway-storage]
path = 'contracts/gateway-storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.hello-world]
path = 'contracts/hello-world.clar'
clarity_version = 2
epoch = 2.5

[contracts.interchain-token-factory]
path = 'contracts/interchain-token-factory.clar'
clarity_version = 2
epoch = 2.5

[contracts.interchain-token-factory-impl]
path = 'contracts/interchain-token-factory-impl.clar'
clarity_version = 2
epoch = 2.5

[contracts.interchain-token-service]
path = 'contracts/interchain-token-service.clar'
clarity_version = 2
epoch = 2.5

[contracts.interchain-token-service-impl]
path = 'contracts/interchain-token-service-impl.clar'
clarity_version = 2
epoch = 2.5

[contracts.interchain-token-service-storage]
path = 'contracts/interchain-token-service-storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.native-interchain-token]
path = 'contracts/native-interchain-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.sample-sip-010]
path = 'contracts/sample-sip-010.clar'
clarity_version = 2
epoch = 2.5

[contracts.token-manager]
path = 'contracts/token-manager.clar'
clarity_version = 2
epoch = 2.5

[repl]
costs_version = 2
parser_version = 2
