[project]
name = 'stacks-axelar'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.gas-service]
path = 'contracts/gas-service.clar'
clarity_version = 2
epoch = 2.5

[contracts.gateway]
path = 'contracts/gateway.clar'
clarity_version = 2
epoch = 2.5

[contracts.hello-world]
path = 'contracts/hello-world.clar'
clarity_version = 2
epoch = 2.5

[contracts.traits]
path = 'contracts/traits.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
